[theme]
base="light"
primaryColor="#f97316"
backgroundColor="#f4f8fc"
secondaryBackgroundColor="#ffffff"
textColor="#17324d"
font="sans serif"

[server]
headless=true
enableCORS=false
enableXsrfProtection=false
